# Generated by Django 5.0.3 on 2024-05-15 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contractor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certifications.certifications')),
            ],
        ),
    ]
