# Generated by Django 5.0.3 on 2024-06-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='advance',
            field=models.BooleanField(default=False),
        ),
    ]
