# Generated by Django 5.0.3 on 2024-06-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contracts_advance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='advance',
        ),
    ]
