# Generated by Django 5.0.3 on 2024-03-31 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('GOODS', 'Bienes'), ('SERVICES', 'Servicios'), ('WORKS', 'Obras'), ('CONSULTING', 'Consultoría')], max_length=255)),
                ('budget_item', models.CharField(max_length=255)),
                ('cpc', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('budget', models.FloatField()),
                ('description', models.TextField()),
                ('period', models.IntegerField()),
                ('bid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HiringProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('common', 'Común'), ('special', 'Especial'), ('not_applicable', 'No aplica')], default='not_applicable', max_length=255)),
                ('product_type', models.CharField(choices=[('normalized', 'Normalizado'), ('not_normalized', 'No normalizado'), ('not_applicable', 'No aplica')], default='not_applicable', max_length=255)),
                ('procedure', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('GOODS', 'Bienes'), ('SERVICES', 'Servicios'), ('WORKS', 'Obras'), ('CONSULTING', 'Consultoría')], max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('budget', models.FloatField()),
                ('description', models.TextField()),
                ('period', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_bid', to='budget_items.budgetitem')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_budget_item', to='budget_items.budgetitem')),
                ('cpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_cpc', to='budget_items.budgetitem')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_product_type', to='budget_items.budgetitem')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_department', to='budget_items.department')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_procedure', to='budget_items.hiringproceduretype')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_regime', to='budget_items.hiringproceduretype')),
            ],
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items_procedure', to='budget_items.hiringproceduretype'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items_product_type', to='budget_items.hiringproceduretype'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items_regime', to='budget_items.hiringproceduretype'),
        ),
    ]
