# Generated by Django 5.0.3 on 2024-05-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitems',
            name='budget_type',
            field=models.CharField(choices=[('Gasto Corriente', 'Gasto Corriente'), ('Proyecto de Inversión', 'Proyecto de Inversión')], max_length=21),
        ),
    ]
