# Generated by Django 5.0.3 on 2024-04-03 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItems',
            fields=[
                ('budget_item', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cpc', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('budget', models.FloatField()),
                ('budget_type', models.CharField(choices=[('GC', 'Gasto Corriente'), ('PI', 'Proyecto de Inversión')], max_length=2)),
                ('description', models.TextField()),
                ('bid', models.BooleanField()),
                ('regime', models.CharField(max_length=1)),
                ('product_type', models.CharField(max_length=2)),
                ('purchase_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProceduresTypes',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('regime', models.CharField(choices=[('C', 'Común'), ('S', 'Especial'), ('N', 'No Aplica')], max_length=1)),
                ('product_type', models.CharField(choices=[('N', 'Normalizado'), ('NN', 'No Normalizado'), ('NA', 'No Aplica')], max_length=2)),
                ('purchase_type', models.CharField(choices=[('B', 'Bienes'), ('S', 'Servicios'), ('O', 'Obras'), ('C', 'Consultoría')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='certification',
            name='budget_item',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='cpc',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='department',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='regime',
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('budget', models.FloatField()),
                ('description', models.TextField()),
                ('period', models.IntegerField()),
                ('cpc', models.CharField(max_length=15)),
                ('budget_type', models.CharField(choices=[('GC', 'Gasto Corriente'), ('PI', 'Proyecto de Inversión')], max_length=2)),
                ('bid', models.BooleanField()),
                ('regime', models.CharField(max_length=1)),
                ('product_type', models.CharField(max_length=2)),
                ('purchase_type', models.CharField(max_length=1)),
                ('budget_item_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_items.budgetitems')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_department', to='budget_items.departments')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_procedure', to='budget_items.procedurestypes')),
            ],
        ),
        migrations.AddField(
            model_name='budgetitems',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_items.procedurestypes'),
        ),
        migrations.DeleteModel(
            name='BudgetItem',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='HiringProcedureType',
        ),
    ]
