# Generated by Django 5.0.3 on 2024-04-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_items', '0003_rename_budget_item_budgetitems_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitems',
            name='budget_type',
            field=models.CharField(choices=[('CE', 'Current Expense'), ('IP', 'Investment Project')], max_length=2),
        ),
        migrations.AlterField(
            model_name='procedurestypes',
            name='product_type',
            field=models.CharField(choices=[('N', 'Normalized'), ('NN', 'Not Normalized'), ('NA', 'Not Applicable')], max_length=2),
        ),
        migrations.AlterField(
            model_name='procedurestypes',
            name='purchase_type',
            field=models.CharField(choices=[('G', 'Good'), ('S', 'Service'), ('W', 'Work'), ('C', 'Consultancy')], max_length=1),
        ),
        migrations.AlterField(
            model_name='procedurestypes',
            name='regime',
            field=models.CharField(choices=[('C', 'Common'), ('S', 'Speciall'), ('N', 'Not Applicable')], max_length=1),
        ),
    ]
