# Generated by Django 5.0.3 on 2024-04-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_items', '0004_alter_budgetitems_budget_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='budget_item',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='department',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='procedure',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Certifications',
        ),
        migrations.DeleteModel(
            name='ProceduresTypes',
        ),
    ]
