# Generated by Django 5.0.3 on 2024-04-10 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_items', '0005_remove_certifications_budget_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitems',
            name='id',
            field=models.AutoField(default=datetime.datetime(2024, 4, 10, 3, 45, 39, 295193, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetitems',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
