# Generated by Django 5.0.3 on 2024-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_items', '0008_alter_budgetitems_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitems',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
