# Generated by Django 5.0.3 on 2024-06-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitems',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
