# Generated by Django 5.0.3 on 2024-05-15 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employees')),
            ],
        ),
    ]
