# Generated by Django 5.0.7 on 2024-07-10 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_item', '0001_initial'),
        ('department', '0001_initial'),
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('certification', models.FileField(upload_to='certifications/')),
                ('resolution', models.FileField(blank=True, upload_to='resolutions/')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_item.budgetitem')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.procedure')),
            ],
            options={
                'ordering': ['number', 'budget_item', 'description'],
                'unique_together': {('number', 'budget_item')},
            },
        ),
    ]
