# Generated by Django 5.0.7 on 2024-07-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
        ('department', '0001_initial'),
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.department'),
        ),
        migrations.AddField(
            model_name='certification',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure.procedure'),
        ),
        migrations.AlterUniqueTogether(
            name='certification',
            unique_together={('number', 'budget_item')},
        ),
    ]
