# Generated by Django 5.0.3 on 2024-04-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProceduresTypes',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('regime', models.CharField(choices=[('C', 'Common'), ('S', 'Speciall'), ('N', 'Not Applicable')], max_length=1)),
                ('product_type', models.CharField(choices=[('N', 'Normalized'), ('NN', 'Not Normalized'), ('NA', 'Not Applicable')], max_length=2)),
                ('purchase_type', models.CharField(choices=[('G', 'Good'), ('S', 'Service'), ('W', 'Work'), ('C', 'Consultancy')], max_length=1)),
            ],
        ),
    ]
