# Generated by Django 5.0.3 on 2024-05-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurestypes',
            name='product_type',
            field=models.CharField(choices=[('Normalizado', 'Normalizado'), ('No Normalizado', 'No Normalizado'), ('No Aplica', 'No Aplica')], max_length=14),
        ),
        migrations.AlterField(
            model_name='procedurestypes',
            name='purchase_type',
            field=models.CharField(choices=[('Bien', 'Bien'), ('Servicio', 'Servicio'), ('Obra', 'Obra'), ('Consultoría', 'Consultoría'), ('Bienes y Servicios', 'Bienes y Servicios')], max_length=18),
        ),
        migrations.AlterField(
            model_name='procedurestypes',
            name='regime',
            field=models.CharField(choices=[('Común', 'Común'), ('Especial', 'Especial'), ('No Aplica', 'No Aplica')], max_length=9),
        ),
    ]
