# Generated by Django 5.0.3 on 2024-04-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurestypes',
            name='product_type',
            field=models.CharField(choices=[('Normalized', 'Normalized'), ('Not Normalized', 'Not Normalized'), ('Not Applicable', 'Not Applicable')], max_length=14),
        ),
        migrations.AlterField(
            model_name='procedurestypes',
            name='purchase_type',
            field=models.CharField(choices=[('Good', 'Good'), ('Service', 'Service'), ('Work', 'Work'), ('Consultancy', 'Consultancy'), ('Goods & Services', 'Goods & Services')], max_length=16),
        ),
        migrations.AlterField(
            model_name='procedurestypes',
            name='regime',
            field=models.CharField(choices=[('Common', 'Common'), ('Special', 'Special'), ('Not Applicable', 'Not Applicable')], max_length=14),
        ),
    ]
