# Generated by Django 5.0.3 on 2024-05-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProceduresTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('regime', models.CharField(choices=[('Común', 'Común'), ('Especial', 'Especial'), ('No Aplica', 'No Aplica')], max_length=9)),
                ('product_type', models.CharField(choices=[('Normalizado', 'Normalizado'), ('No Normalizado', 'No Normalizado'), ('No Aplica', 'No Aplica')], max_length=14)),
                ('purchase_type', models.CharField(choices=[('Bien', 'Bien'), ('Servicio', 'Servicio'), ('Obra', 'Obra'), ('Consultoría', 'Consultoría'), ('Bienes y Servicios', 'Bienes y Servicios')], max_length=18)),
            ],
        ),
    ]
