# Generated by Django 5.0.7 on 2024-07-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=25, unique=True)),
                ('contractor', models.CharField(max_length=100)),
                ('duration', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('contract', models.FileField(max_length=1, upload_to='contracts/')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.certification')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AdminHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contract')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
