# Generated by Django 5.0.7 on 2024-07-10 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contractor', models.CharField(max_length=100)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.certification')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
