# Generated by Django 5.0.7 on 2024-07-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['last_name', 'name', 'ci'],
            },
        ),
    ]
