# Generated by Django 5.0.7 on 2024-08-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('first_last_name', models.CharField(max_length=20)),
                ('middle_last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['first_last_name', 'middle_last_name', 'first_name', 'middle_name', 'ci'],
            },
        ),
    ]
