# Generated by Django 5.0.3 on 2024-05-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='period',
            field=models.CharField(choices=[('C1', 'C1'), ('C2', 'C3'), ('C3', 'C3'), ('C1 - C2', 'C1 - C2'), ('C1 - C3', 'C1 - C3'), ('C2 - C3', 'C2 - C3'), ('C1 - C2 - C3', 'C1 - C2 - C3')], max_length=12),
        ),
    ]
