# Generated by Django 5.0.3 on 2024-04-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationsbudgetitems',
            name='certifications_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certifications.certifications'),
        ),
    ]
