# Generated by Django 5.0.3 on 2024-04-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=255)),
            ],
        ),
    ]
