# Generated by Django 5.0.7 on 2024-07-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('N', 'Normalizado'), ('!N', 'No Normalizado')], max_length=2)),
                ('purchase_type', models.CharField(blank=True, choices=[('B', 'Bien'), ('C', 'Consultoría'), ('O', 'Obra'), ('S', 'Servicio')], max_length=1)),
                ('regime', models.CharField(blank=True, choices=[('C', 'Común'), ('E', 'Especial')], max_length=1)),
            ],
            options={
                'ordering': ['name', 'purchase_type', 'product_type'],
            },
        ),
    ]
