# Generated by Django 5.0.7 on 2024-08-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('Normalizado', 'Normalizado'), ('No Normalizado', 'No Normalizado')], max_length=14)),
                ('purchase_type', models.CharField(blank=True, choices=[('Bien', 'Bien'), ('Consultoría', 'Consultoría'), ('Obra', 'Obra'), ('Servicio', 'Servicio')], max_length=11)),
                ('regime', models.CharField(blank=True, choices=[('Común', 'Común'), ('Especial', 'Especial')], max_length=8)),
            ],
            options={
                'ordering': ['name', 'purchase_type', 'product_type', 'regime'],
                'unique_together': {('name', 'purchase_type', 'product_type', 'regime')},
            },
        ),
    ]
