# Generated by Django 5.0.7 on 2024-07-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('name', 'regime', 'product_type', 'purchase_type')},
        ),
    ]
