# Generated by Django 5.0.7 on 2024-07-10 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('cpc', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('activity', models.TextField()),
                ('purchase_type', models.CharField(choices=[('B', 'Bien'), ('C', 'Consultoría'), ('O', 'Obra'), ('S', 'Servicio')], max_length=1)),
                ('budget_type', models.CharField(choices=[('GC', 'Gasto Corriente'), ('PI', 'Proyecto de Inversion')], max_length=2)),
                ('budget', models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('c1', models.BooleanField(default=False)),
                ('c2', models.BooleanField(default=False)),
                ('c3', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number', 'description', 'activity'],
                'unique_together': {('number', 'description', 'activity')},
            },
        ),
    ]
