# Generated by Django 5.0.7 on 2024-07-29 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
